package com.moj.purchaseservice.enums;

public enum OrderAnalyzeContentStatus {
    PENDING,
    PAYMENT_FAILED,
    SERVER_FAILED,
    PURCHASED,
    FAIL_TO_SCRAPE,
    SCRAPING_COMPLETED,
    PICKUP_VIDEOS_COMPLETED,
    ANALYZE_CONTENT_COMPLETED,
    ANALYZE_CONTENT_FAILED,
    SUCCEED,
    FAILED_TO_REFUND,
    REFUND_COMPLETED,
}
