server:
  port: 8762

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/api/auth/**
            - id: user-service-route
              uri: ${USER_SERVICE_URL}
              predicates:
                - Path=/api/user/**
            - id: purchase-service-route
              uri: ${PURCHASE_SERVICE_URL}
              predicates:
                - Path=/api/purchase/**
              filters:
                - name: RequestSize
                  args:
                    maxSize: 2GB
            - id: llm-service-route
              uri: ${LLM_SERVICE_URL}
              predicates:
                - Path=/api/llm/**
jwt:
  secret-key: ${JWT_SECRET_KEY}
logging:
  level:
    root: INFO

    # החלף ב-package האמיתי של ה-Gateway שלך
    com.moj.apigateway: DEBUG

    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO

    # חיבורי HTTP של WebFlux
    reactor.netty.http.client: INFO
    reactor.netty.http.server: INFO