server:
  port: 8762

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: ${AUTH_SERVICE_URL:http://localhost:8080}
              predicates:
                - Path=/api/auth/**

jwt:
  secret-key: ${JWT_SECRET_KEY}
logging:
  level:
    root: INFO

    # החלף ב-package האמיתי של ה-Gateway שלך
    com.moj.apigateway: DEBUG

    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO

    # חיבורי HTTP של WebFlux
    reactor.netty.http.client: INFO
    reactor.netty.http.server: INFO