spring.application.name=userService
server.port=8082
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

logging.level.root=INFO
logging.level.com.moj.userservice=INFO

# RabbitMQ Consumer Retry Limit

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-retries=3
spring.rabbitmq.listener.simple.retry.initial-interval=1s
spring.rabbitmq.listener.simple.retry.multiplier=2
spring.rabbitmq.listener.simple.retry.max-interval=5s
spring.rabbitmq.listener.simple.default-requeue-rejected=false


# RabbitMQ Producer Retry Limit

spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.max-retries=3
spring.rabbitmq.template.retry.initial-interval=1s
spring.rabbitmq.template.retry.multiplier=2
spring.rabbitmq.template.retry.max-interval=5s
